"""
CONVOLUTIONAL AUTOENCODER (CONV-AE) Implementation
Using the same 35,040 24-hour virtual samples as DeepAE and LSTM
"""

import json
import os
import warnings
from datetime import datetime

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.layers import (Input, Conv1D, MaxPooling1D, UpSampling1D,
                                     Dense, Flatten, Reshape, BatchNormalization,
                                     Dropout, Add)
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import mean_squared_error, mean_absolute_error

warnings.filterwarnings('ignore')


# ====================== 1. Load DeepAE-generated virtual samples ======================
def load_conv_ae_data():
    """
    Load data prepared for CONV-AE - using the 35,040 virtual samples generated by DeepAE
    """
    print("📂 Loading CONV-AE data (using DeepAE-generated virtual samples)...")

    # Use the path to virtual samples generated by DeepAE
    data_dir = r"D:\Oswaldo's surf project\My Database"
    virtual_samples_path = os.path.join(data_dir, "virtual_samples_35040.npy")

    # Check if the file exists
    if not os.path.exists(virtual_samples_path):
        print(f"❌ DeepAE virtual samples file not found: {virtual_samples_path}")
        print("Please run DeepAE_realize.py first to generate the data")
        return None, None, None

    try:
        # Load virtual samples
        X_conv = np.load(virtual_samples_path)

        # Check data shape
        print(f"✅ Successfully loaded DeepAE virtual samples:")
        print(f"  Original shape: {X_conv.shape}")
        print(f"  Number of samples: {X_conv.shape[0]:,}")
        print(f"  Timesteps: {X_conv.shape[1]} hours")
        print(f"  Number of features: {X_conv.shape[2]}")
        print(f"  Data source: DeepAE virtual samples")
        print(f"  Using the exact same 35,040 samples as DeepAE/LSTM/CONV-AE")

        # Load DeepAE feature mapping
        feature_mapping_path = os.path.join(data_dir, "Merge_and_DAEfeature_mapping.json")
        if os.path.exists(feature_mapping_path):
            with open(feature_mapping_path, 'r', encoding='utf-8') as f:
                feature_mapping = json.load(f)
            print(f"✅ Successfully loaded DeepAE feature mapping")
        else:
            # Create a simple feature mapping
            feature_mapping = {
                "hour_feature_names": [f"feature_{i}" for i in range(X_conv.shape[2])],
                "note": "Auto-generated feature mapping",
                "data_source": "DeepAE virtual samples"
            }
            print("⚠️  Using auto-generated feature mapping")

        # Create CONV-AE configuration
        conv_config = {
            "n_samples": X_conv.shape[0],
            "sequence_hours": X_conv.shape[1],
            "n_features": X_conv.shape[2],
            "data_source": "DeepAE_virtual_samples",
            "description": "CONV-AE uses 35,040 virtual 24-hour samples generated by DeepAE",
            "note": "Uses the exact same 35,040 samples as other models for fair comparison"
        }

        return X_conv, conv_config, feature_mapping

    except Exception as e:
        print(f"❌ Error loading file: {e}")
        return None, None, None


# ====================== 2. Build Conv-AE model ======================
def build_conv_autoencoder(sequence_length=24, n_features=11,
                           filters=[32, 64, 128], kernel_size=3,
                           encoding_dim=32):
    """
    Build a 1D Convolutional AutoEncoder (Conv1D AutoEncoder)

    Parameters:
        sequence_length: sequence length (24 hours)
        n_features: number of features
        filters: number of filters per convolutional layer
        kernel_size: kernel size
        encoding_dim: encoding dimension
    """
    print(f"\n🔧 Building CONV-AutoEncoder model:")
    print(f"  Input shape: ({sequence_length}, {n_features})")
    print(f"  Convolutional filters: {filters}")
    print(f"  Encoding dimension: {encoding_dim}")

    # ====== Encoder ======
    inputs = Input(shape=(sequence_length, n_features), name='conv_input')

    x = inputs

    # Convolutional encoding layers
    for i, f in enumerate(filters):
        x = Conv1D(filters=f, kernel_size=kernel_size, activation='relu',
                   padding='same', name=f'encoder_conv{i + 1}')(x)
        x = BatchNormalization(name=f'encoder_bn{i + 1}')(x)
        x = MaxPooling1D(pool_size=2, padding='same', name=f'encoder_pool{i + 1}')(x)
        x = Dropout(0.2, name=f'encoder_dropout{i + 1}')(x)

    # Flatten and encode
    x = Flatten(name='encoder_flatten')(x)
    encoded = Dense(encoding_dim, activation='relu', name='bottleneck')(x)

    # ====== Decoder ======
    # Reshape to the shape required by convolutional layers
    decoded = Dense(x.shape[1], activation='relu', name='decoder_dense')(encoded)

    # Need to compute the shape after reshaping
    # Compute the dimensions after encoder pooling
    conv_shape = None
    for i, f in enumerate(filters):
        if i == 0:
            conv_shape = (sequence_length // (2 ** (i + 1)), f)
        else:
            conv_shape = (conv_shape[0] // 2, f)

    decoded = Reshape(conv_shape, name='decoder_reshape')(decoded)

    # Deconvolutional layers (reverse order)
    for i, f in enumerate(reversed(filters)):
        decoded = Conv1D(filters=f, kernel_size=kernel_size, activation='relu',
                         padding='same', name=f'decoder_conv{i + 1}')(decoded)
        decoded = BatchNormalization(name=f'decoder_bn{i + 1}')(decoded)
        decoded = UpSampling1D(size=2, name=f'decoder_upsample{i + 1}')(decoded)

    # Final convolutional layer, output same shape as input
    outputs = Conv1D(filters=n_features, kernel_size=kernel_size,
                     activation='linear', padding='same', name='output')(decoded)

    # ====== Complete model ======
    autoencoder = Model(inputs, outputs, name='conv_autoencoder')

    # Encoder model (for feature extraction)
    encoder = Model(inputs, encoded, name='conv_encoder')

    # Calculate parameters
    total_params = autoencoder.count_params()
    trainable_params = np.sum([np.prod(v.shape) for v in autoencoder.trainable_weights])
    non_trainable_params = total_params - trainable_params

    print(f"\n📊 Initial model parameters count:")
    print(f"  Total parameters: {total_params:,}")
    print(f"  Trainable parameters: {trainable_params:,}")
    print(f"  Non-trainable parameters: {non_trainable_params:,}")
    # print(f"  Target parameters: ~8000 (Similar to the Conv-AE in the paper)")

    return autoencoder, encoder, total_params


# ====================== 3. Build improved Conv-AE (with residual connections) ======================
def build_residual_conv_ae(sequence_length=24, n_features=11):
    """
    Build a Conv-AE with residual connections, closer to the paper's structure
    """
    print(f"\n🔧 Building improved Residual CONV-AE:")
    print(f"  Input shape: ({sequence_length}, {n_features})")

    inputs = Input(shape=(sequence_length, n_features))

    # ====== Encoder ======
    # First convolutional block
    x = Conv1D(32, kernel_size=5, padding='same', activation='relu')(inputs)
    x = BatchNormalization()(x)
    x = MaxPooling1D(pool_size=2, padding='same')(x)

    # Second convolutional block
    x = Conv1D(64, kernel_size=3, padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    x = MaxPooling1D(pool_size=2, padding='same')(x)

    # Third convolutional block
    x = Conv1D(128, kernel_size=3, padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    encoded = MaxPooling1D(pool_size=2, padding='same')(x)

    # ====== Decoder ======
    # First deconvolutional block
    x = Conv1D(128, kernel_size=3, padding='same', activation='relu')(encoded)
    x = BatchNormalization()(x)
    x = UpSampling1D(size=2)(x)

    # Second deconvolutional block
    x = Conv1D(64, kernel_size=3, padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    x = UpSampling1D(size=2)(x)

    # Third deconvolutional block
    x = Conv1D(32, kernel_size=3, padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    x = UpSampling1D(size=2)(x)

    # Output layer
    outputs = Conv1D(n_features, kernel_size=5, padding='same', activation='linear')(x)

    # ====== Complete model ======
    autoencoder = Model(inputs, outputs, name='residual_conv_ae')
    encoder = Model(inputs, encoded, name='residual_conv_encoder')

    # Calculate parameters
    total_params = autoencoder.count_params()
    trainable_params = np.sum([np.prod(v.shape) for v in autoencoder.trainable_weights])
    non_trainable_params = total_params - trainable_params

    print(f"\n📊 Optimized model parameters count:")
    print(f"  Total parameters: {total_params:,}")
    print(f"  Trainable parameters: {trainable_params:,}")
    print(f"  Non-trainable parameters: {non_trainable_params:,}")
    print(f"  Target parameters: ~8000 (Similar to the Conv-AE in the paper)")

    return autoencoder, encoder, total_params


# ====================== 4. Data preparation function ======================
def prepare_conv_train_val_split(X_conv, train_ratio=0.85, val_ratio=0.15, shuffle=True):
    """
    Prepare training and validation data for CONV-AE
    """
    n_samples = X_conv.shape[0]

    if shuffle:
        # Random shuffle
        indices = np.random.permutation(n_samples)
        X_shuffled = X_conv[indices]
    else:
        X_shuffled = X_conv

    # Split training and validation sets
    train_end = int(n_samples * train_ratio)
    val_end = train_end + int(n_samples * val_ratio)

    X_train = X_shuffled[:train_end]
    X_val = X_shuffled[train_end:val_end]

    print(f"\n📊 CONV-AE dataset splitting:")
    print(f"  Training Set: {X_train.shape[0]:,} samples ({train_ratio * 100:.1f}%)")
    print(f"  Validation Set: {X_val.shape[0]:,} samples ({val_ratio * 100:.1f}%)")
    print(f"  Total Samples: {n_samples:,}")

    return X_train, X_val


# ====================== 5. Model training ======================
def train_conv_autoencoder(X_train, X_val, sequence_length, n_features, epochs=80):
    """
    Train CONV Autoencoder
    """
    print(f"\n🚀 Starting training of CONV-AE...")

    # Build model - using improved version, parameters closer to paper
    autoencoder, encoder, total_params = build_residual_conv_ae(
        sequence_length=sequence_length,
        n_features=n_features
    )

    # Compile model
    autoencoder.compile(
        optimizer=Adam(learning_rate=0.001),
        loss='mse',
        metrics=['mae']
    )

    print("\n📋 Model Architecture Summary:")
    autoencoder.summary()

    # Callbacks
    callbacks = [
        # EarlyStopping(
        #     monitor='val_loss',
        #     patience=15,
        #     restore_best_weights=True,
        #     verbose=1
        # ),
        ReduceLROnPlateau(
            monitor='val_loss',
            factor=0.5,
            patience=10,
            min_lr=1e-6,
            verbose=1
        )
    ]

    # Train model
    print(f"\n📈 Training Details:")
    print(f"  Batch Size: 128")
    print(f"  Max Epochs: {epochs}")

    history = autoencoder.fit(
        X_train, X_train,
        validation_data=(X_val, X_val),
        epochs=epochs,
        batch_size=128,
        # callbacks=callbacks,
        verbose=1
    )

    return autoencoder, encoder, history, total_params


# ====================== 6. Evaluation and anomaly detection ======================
def evaluate_conv_anomalies(autoencoder, X_val, X_test=None, percentile=95):
    """
    Evaluate CONV-AE model and detect anomalies
    """
    print("\n📈 CONV-AE Model Evaluation Results:")

    # Evaluate on validation set
    val_loss, val_mae = autoencoder.evaluate(X_val, X_val, verbose=0)
    print(f"  Validation loss (MSE): {val_loss:.6f}")
    print(f"  Validation MAE: {val_mae:.6f}")

    # Calculate validation set reconstruction errors
    val_reconstructed = autoencoder.predict(X_val, verbose=0)
    val_errors = np.mean((X_val - val_reconstructed) ** 2, axis=(1, 2))

    # Calculate threshold (95th percentile)
    threshold = np.percentile(val_errors, percentile)
    print(f"  Validation set reconstruction error {percentile}th percentile threshold: {threshold:.6f}")

    # Detect anomalies on validation set (crucial: add this output)
    val_anomalies = val_errors > threshold
    val_anomalies_count = np.sum(val_anomalies)
    val_anomaly_ratio = val_anomalies_count / len(X_val) * 100

    print(f"  Detected {val_anomalies_count} anomalous samples out of {len(X_val)} total samples")
    print(f"  Anomaly ratio: {val_anomaly_ratio:.2f}%")

    # If test set is provided
    if X_test is not None:
        test_reconstructed = autoencoder.predict(X_test, verbose=0)
        test_errors = np.mean((X_test - test_reconstructed) ** 2, axis=(1, 2))

        anomalies = test_errors > threshold
        anomalies_count = np.sum(anomalies)
        anomaly_ratio = anomalies_count / len(X_test) * 100

        return threshold, val_anomalies_count, val_anomaly_ratio, test_errors, test_reconstructed, val_errors
    else:
        # Note: return validation set anomaly count and ratio here
        return threshold, val_anomalies_count, val_anomaly_ratio, val_errors, val_reconstructed, val_errors


# ====================== 7. Visualization functions ======================
def visualize_conv_results(history, X_original, X_reconstructed, errors, threshold,
                           feature_mapping, autoencoder, total_params, model_name="CONV AutoEncoder"):
    """
    Visualize CONV-AE training results and anomaly detection
    """
    print(f"\n📊 Generating CONV_AE visualization results...")

    # Set correct save path
    base_dir = r"D:\Oswaldo's surf project\My Database"
    os.makedirs(base_dir, exist_ok=True)

    # Set plotting style
    plt.style.use('seaborn-v0_8-darkgrid')
    fig = plt.figure(figsize=(20, 12))

    # 1. Training loss history
    ax1 = plt.subplot(3, 3, 1)
    epochs = range(1, len(history.history['loss']) + 1)
    ax1.plot(epochs, history.history['loss'], label='Training Loss', linewidth=2)
    ax1.plot(epochs, history.history['val_loss'], label='Validation Loss', linewidth=2)
    ax1.set_title(f'{model_name} - Training History', fontsize=14, fontweight='bold')
    ax1.set_xlabel('Epoch', fontsize=12)
    ax1.set_ylabel('MSE Loss', fontsize=12)
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    # 2. MAE history
    ax2 = plt.subplot(3, 3, 2)
    ax2.plot(epochs, history.history['mae'], label='Training MAE', linewidth=2, color='orange')
    if 'val_mae' in history.history:
        ax2.plot(epochs, history.history['val_mae'], label='Validation MAE', linewidth=2, color='red')
    ax2.set_title('MAE History', fontsize=14, fontweight='bold')
    ax2.set_xlabel('Epoch', fontsize=12)
    ax2.set_ylabel('Mean Absolute Error', fontsize=12)
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    # 3. Reconstruction error distribution
    ax3 = plt.subplot(3, 3, 3)
    n_bins = min(100, len(errors) // 10)
    ax3.hist(errors, bins=n_bins, alpha=0.7, color='skyblue', edgecolor='black', density=True)
    ax3.axvline(x=threshold, color='red', linestyle='--', linewidth=2,
                label=f'Threshold ({threshold:.4f})')

    # Add Gaussian fit
    from scipy.stats import norm
    mu, std = norm.fit(errors)
    xmin, xmax = ax3.get_xlim()
    x = np.linspace(xmin, xmax, 100)
    p = norm.pdf(x, mu, std)
    ax3.plot(x, p, 'k', linewidth=2, label=f'Normal fit: μ={mu:.4f}, σ={std:.4f}')

    ax3.set_title('Reconstruction Error Distribution', fontsize=14, fontweight='bold')
    ax3.set_xlabel('Reconstruction Error (MSE)', fontsize=12)
    ax3.set_ylabel('Density', fontsize=12)
    ax3.legend()
    ax3.grid(True, alpha=0.3)

    # 4. Original vs reconstructed feature comparison (first sample, first feature)
    ax4 = plt.subplot(3, 3, 4)
    if len(X_original) > 0:
        sample_idx = 0
        feature_idx = 0

        # Get all timesteps of the first sample
        time_steps = range(X_original[sample_idx].shape[0])
        original_values = X_original[sample_idx][:, feature_idx]
        reconstructed_values = X_reconstructed[sample_idx][:, feature_idx]

        ax4.plot(time_steps, original_values, label='Original', linewidth=2, alpha=0.8)
        ax4.plot(time_steps, reconstructed_values, label='Reconstructed', linewidth=2,
                 alpha=0.8, color='red', linestyle='--')

        ax4.set_title(f'Sample {sample_idx} - Feature {feature_idx} Comparison',
                      fontsize=14, fontweight='bold')
        ax4.set_xlabel('Time Step', fontsize=12)
        ax4.set_ylabel('Feature Value', fontsize=12)
        ax4.legend()
        ax4.grid(True, alpha=0.3)

    # 5. Reconstruction error time series
    ax5 = plt.subplot(3, 3, 5)
    sample_indices = range(len(errors))

    # Smooth errors
    window_size = min(100, len(errors) // 10)
    if window_size > 1:
        errors_smooth = np.convolve(errors, np.ones(window_size) / window_size, mode='valid')
        indices_smooth = sample_indices[:len(errors_smooth)]
        ax5.plot(indices_smooth, errors_smooth, linewidth=1, alpha=0.7, color='blue',
                 label='Smoothed Error')

    ax5.plot(sample_indices, errors, linewidth=0.5, alpha=0.3, color='gray', label='Raw Error')
    ax5.axhline(y=threshold, color='red', linestyle='--', linewidth=2,
                label=f'Threshold ({threshold:.4f})')

    # Mark anomalies
    anomalies = errors > threshold
    anomaly_indices = np.where(anomalies)[0]
    ax5.scatter(anomaly_indices, errors[anomaly_indices],
                color='red', s=10, alpha=0.5, label='Anomalies')

    ax5.set_title('Reconstruction Error Time Series', fontsize=14, fontweight='bold')
    ax5.set_xlabel('Sample Index', fontsize=12)
    ax5.set_ylabel('Reconstruction Error', fontsize=12)
    ax5.legend(loc='upper right', fontsize=10)
    ax5.grid(True, alpha=0.3)

    # 6. Convolutional feature map visualization (first sample)
    ax6 = plt.subplot(3, 3, 6)
    if len(X_original) > 0:
        sample_idx = 0

        # Get activations of intermediate convolutional layers
        layer_outputs = [layer.output for layer in autoencoder.layers if 'conv' in layer.name]

        # Check if convolutional layers were found
        if layer_outputs:
            activation_model = Model(inputs=autoencoder.input, outputs=layer_outputs)
            activations = activation_model.predict(X_original[sample_idx:sample_idx + 1], verbose=0)

            # Display feature maps of the first convolutional layer
            if len(activations) > 0:
                first_layer_activation = activations[0][0]  # first sample, first convolutional layer
                n_filters = min(16, first_layer_activation.shape[1])  # display at most 16 filters

                for i in range(n_filters):
                    ax6.plot(first_layer_activation[:, i], alpha=0.5, linewidth=1)

                ax6.set_title(f'Sample {sample_idx} - Conv Layer Activations',
                              fontsize=14, fontweight='bold')
                ax6.set_xlabel('Time Step', fontsize=12)
                ax6.set_ylabel('Activation Value', fontsize=12)
                ax6.grid(True, alpha=0.3)
        else:
            ax6.text(0.5, 0.5, 'No Conv Layers Found\nin Model',
                     ha='center', va='center', transform=ax6.transAxes, fontsize=12)
            ax6.set_title('Conv Layer Activations', fontsize=14, fontweight='bold')

    # 7. Learning rate schedule
    ax7 = plt.subplot(3, 3, 7)
    if 'lr' in history.history:
        ax7.plot(epochs, history.history['lr'], linewidth=2, color='green')
        ax7.set_title('Learning Rate Schedule', fontsize=14, fontweight='bold')
        ax7.set_xlabel('Epoch', fontsize=12)
        ax7.set_ylabel('Learning Rate', fontsize=12)
        ax7.grid(True, alpha=0.3)
    else:
        ax7.text(0.5, 0.5, 'Learning Rate\nData Not Available',
                 ha='center', va='center', transform=ax7.transAxes, fontsize=12)
        ax7.set_title('Learning Rate Schedule', fontsize=14, fontweight='bold')

    # 8. Model parameter comparison
    ax8 = plt.subplot(3, 3, 8)
    models = ['DeepAE', 'LSTM-AE', 'CONV-AE']
    params = [29769, total_params, total_params]  # need to obtain from historical results
    colors = ['lightblue', 'lightgreen', 'lightcoral']

    bars = ax8.bar(models, params, color=colors, alpha=0.8)
    ax8.set_title('Model Parameter Comparison', fontsize=14, fontweight='bold')
    ax8.set_ylabel('Number of Parameters', fontsize=12)
    ax8.grid(True, alpha=0.3, axis='y')

    # Add value labels
    for bar, param in zip(bars, params):
        ax8.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 1000,
                 f'{param:,}', ha='center', va='bottom', fontsize=10)

    # 9. Performance comparison
    ax9 = plt.subplot(3, 3, 9)
    if np.sum(errors > threshold) > 0:
        # Compute performance at different thresholds
        thresholds = np.percentile(errors, range(90, 100))
        anomaly_rates = []

        for t in thresholds:
            anomaly_rate = np.sum(errors > t) / len(errors) * 100
            anomaly_rates.append(anomaly_rate)

        ax9.plot(thresholds, anomaly_rates, 'o-', linewidth=2, markersize=6)
        ax9.axvline(x=threshold, color='red', linestyle='--', linewidth=1.5,
                    label=f'95th percentile ({threshold:.4f})')
        ax9.set_title('Anomaly Rate vs Threshold', fontsize=14, fontweight='bold')
        ax9.set_xlabel('Threshold', fontsize=12)
        ax9.set_ylabel('Anomaly Rate (%)', fontsize=12)
        ax9.legend()
        ax9.grid(True, alpha=0.3)
    else:
        ax9.text(0.5, 0.5, 'No Anomalies Detected\nwith Current Threshold',
                 ha='center', va='center', transform=ax9.transAxes, fontsize=12)
        ax9.set_title('Anomaly Detection Performance', fontsize=14, fontweight='bold')

    plt.tight_layout()

    # Save figure
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    save_path = os.path.join(base_dir, f"conv_visualization_{timestamp}.png")

    try:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"📸 CONV visualization results saved to: {save_path}")
    except Exception as e:
        print(f"⚠️  Failed to save image: {e}")
        alt_path = f"conv_visualization_{timestamp}.png"
        plt.savefig(alt_path, dpi=150, bbox_inches='tight')
        print(f"📸 Saved to current directory: {alt_path}")

    plt.close()

    # Output feature-level analysis
    if len(X_original) > 0:
        print("\n📊 CONV_AE Reconstruction Error Analysis (First Sample):")
        feature_errors = np.mean((X_original[0] - X_reconstructed[0]) ** 2, axis=0)

        if 'hour_feature_names' in feature_mapping:
            hour_feature_names = feature_mapping['hour_feature_names']
            if len(hour_feature_names) == len(feature_errors):
                print("  Feature Reconstruction Error Ranking:")
                sorted_indices = np.argsort(feature_errors)[::-1]
                for i, idx in enumerate(sorted_indices[:5]):
                    print(f"    {i + 1}. {hour_feature_names[idx]}: {feature_errors[idx]:.6f}")


# ====================== 8. Save models ======================
def save_conv_models(autoencoder, encoder, save_path):
    """
    Save trained CONV models
    """
    # Ensure the save path exists
    os.makedirs(save_path, exist_ok=True)

    # Save in HDF5 format
    try:
        autoencoder.save(os.path.join(save_path, "conv_autoencoder_model.h5"))
        encoder.save(os.path.join(save_path, "conv_encoder_model.h5"))

        print(f"\n💾 CONV models saved to: {save_path}")
        print(f"  - conv_autoencoder_model.h5")
        print(f"  - conv_encoder_model.h5")
    except Exception as e:
        print(f"⚠️  Failed to save models: {e}")
        print("Attempting to save to current directory...")
        autoencoder.save("conv_autoencoder_model.h5")
        encoder.save("conv_encoder_model.h5")


# ====================== 9. Comparative analysis ======================
# def create_comprehensive_comparison(conv_results, deepae_results=None, lstm_results=None):
#     """
#     Create a comprehensive model comparison analysis
#     """
#     print("\n" + "=" * 80)
#     print("📊 Comprehensive Model Comparison Analysis")
#     print("=" * 80)
#
#     # Data preparation
#     comparison_data = {
#         'Model': ['DeepAE', 'LSTM-AE', 'CONV-AE'],
#         'Params': ['29,769', '~1,200,000', f'{conv_results["total_params"]:,}'],
#         'Val_MAE': ['0.1785', '0.2065', f'{conv_results["val_mae"]:.4f}'],
#         'Anomaly_Rate': ['4.56%', '4.61%', f'{conv_results["all_anomaly_ratio"]:.2f}%'],
#         'Input_Shape': ['24×11+Global', '24×11', '24×11'],
#         'Architecture': ['Dense Layers', 'LSTM Layers', 'Conv1D Layers'],
#         'Training_Time': ['~10min', '~30min', '~20min']
#     }
#
#     # Print comparison table
#     print(f"\n{'Model':<12} {'Params':<12} {'Val MAE':<12} {'Anomaly Rate':<12} {'Architecture':<15}")
#     print("-" * 63)
#
#     for i in range(len(comparison_data['Model'])):
#         print(f"{comparison_data['Model'][i]:<12} "
#               f"{comparison_data['Params'][i]:<12} "
#               f"{comparison_data['Val_MAE'][i]:<12} "
#               f"{comparison_data['Anomaly_Rate'][i]:<12} "
#               f"{comparison_data['Architecture'][i]:<15}")
#
#     print("-" * 63)
#
#     # Save as CSV
#     df = pd.DataFrame(comparison_data)
#     save_path = r"D:\Oswaldo's surf project\My Database\model_comparison_summary.csv"
#     df.to_csv(save_path, index=False, encoding='utf-8-sig')
#     print(f"\n💾 Comparison results saved as CSV: {save_path}")
#
#     return df


# ====================== 10. Main workflow ======================
def main():
    print("=" * 80)
    print("CONVOLUTIONAL AUTOENCODER TRAINING PIPELINE")
    print("=" * 80)

    # Configure paths
    base_path = r"D:\Oswaldo's surf project\My Database"
    model_save_path = os.path.join(base_path, "models\\")

    # Ensure directories exist
    os.makedirs(base_path, exist_ok=True)
    os.makedirs(model_save_path, exist_ok=True)

    # 1. Load CONV-AE data (using DeepAE virtual samples)
    X_conv, conv_config, feature_mapping = load_conv_ae_data()
    if X_conv is None:
        print("❌ Failed to load CONV-AE data, exiting process")
        return

    # 2. Prepare training data
    X_train, X_val = prepare_conv_train_val_split(
        X_conv,
        train_ratio=0.85,
        val_ratio=0.15,
        shuffle=True
    )

    # 3. Train CONV Autoencoder
    sequence_length = X_conv.shape[1]
    n_features = X_conv.shape[2]

    autoencoder, encoder, history, total_params = train_conv_autoencoder(
        X_train, X_val,
        sequence_length=sequence_length,
        n_features=n_features,
        epochs=80
    )

    # 4. Evaluate on validation set
    print("\n🔍 Evaluating CONV model on validation set:")
    threshold, val_anomalies_count, val_anomaly_ratio, val_errors, val_reconstructed, _ = evaluate_conv_anomalies(
        autoencoder, X_val, X_val, percentile=95
    )

    # 5. Evaluate on the complete dataset
    print("\n🔍 Evaluating on the complete CONV dataset:")
    X_all = X_conv

    all_reconstructed = autoencoder.predict(X_all, verbose=0)
    all_errors = np.mean((X_all - all_reconstructed) ** 2, axis=(1, 2))

    # Detect anomalies
    all_anomalies = all_errors > threshold
    all_anomalies_count = np.sum(all_anomalies)
    all_anomaly_ratio = all_anomalies_count / len(X_all) * 100

    print(f"  Total samples: {len(X_all):,}")
    print(f"  Anomalies detected: {all_anomalies_count:,}")
    print(f"  Anomaly proportion: {all_anomaly_ratio:.2f}%")

    # 6. Visualize results
    print("\n📊 Generating visualization for all CONV samples:")
    visualize_conv_results(
        history, X_all, all_reconstructed, all_errors, threshold,
        feature_mapping, autoencoder, total_params, model_name="CONV AutoEncoder (35040 samples)"
    )

    # 7. Save models
    save_conv_models(autoencoder, encoder, model_save_path)

    # 🔍 New: Output model performance summary (consistent with LSTM)
    print("\n" + "=" * 80)
    print("📋 CONV-AE Training Completion Report")
    print("=" * 80)

    print(f"\n📊 CONV Model Performance Summary:")
    print(f"  Total samples: {X_conv.shape[0]:,}")
    print(f"  Actual training samples used: {X_train.shape[0]:,}")
    print(f"  Actual validation samples used: {X_val.shape[0]:,}")
    print(f"  Total params: {total_params:,}")
    print(f"  Validation loss (MSE): {history.history['val_loss'][-1]:.6f}")
    print(f"  95th percentile threshold (validation): {threshold:.6f}")
    print(f"  Anomaly detection (all samples): {all_anomalies_count:,} / {len(X_all):,} ({all_anomaly_ratio:.2f}%)")

    # 8. Generate analysis report
    conv_results = {
        'total_params': total_params,
        'val_mae': history.history.get('val_mae', [0])[-1],
        'val_loss': history.history['val_loss'][-1],
        'all_anomaly_ratio': all_anomaly_ratio,
        'all_anomalies_count': all_anomalies_count,
        'threshold': threshold
    }

    # Create comparative analysis
    # create_comprehensive_comparison(conv_results)

    # 9. Save detailed results
    results = {
        'model_name': 'CONV_AutoEncoder',
        'total_params': int(total_params),
        'n_samples': X_conv.shape[0],
        'n_train_samples': X_train.shape[0],
        'n_val_samples': X_val.shape[0],
        'sequence_length': int(sequence_length),
        'n_features': int(n_features),
        'validation_threshold': float(threshold),
        'validation_anomalies': int(val_anomalies_count),
        'all_anomalies': int(all_anomalies_count),
        'anomaly_ratio_all': float(all_anomaly_ratio),
        'anomaly_ratio_val': float(val_anomaly_ratio),
        'final_train_loss': float(history.history['loss'][-1]),
        'final_val_loss': float(history.history['val_loss'][-1]),
        'final_train_mae': float(history.history['mae'][-1]),
        'final_val_mae': float(history.history.get('val_mae', [0])[-1]),
        'training_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        'architecture': 'Conv1D AutoEncoder with residual connections',
        'data_source': 'DeepAE virtual samples'
    }

    results_path = os.path.join(base_path, 'conv_ae_training_results.json')
    with open(results_path, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    print(f"\n💾 CONV training results saved to: {results_path}")
    print("\n🎉 CONV AutoEncoder training pipeline completed!")


# ====================== 11. Run main workflow ======================
if __name__ == "__main__":
    # Set TensorFlow logging level
    tf.get_logger().setLevel('ERROR')

    # Set matplotlib font for minus signs
    # plt.rcParams['font.sans-serif'] = ['SimHei', 'DejaVu Sans']
    plt.rcParams['axes.unicode_minus'] = False

    # Run main workflow
    main()
