import json
import os
import warnings
from datetime import datetime

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.layers import Input, LSTM, RepeatVector, TimeDistributed, Dense, Dropout, BatchNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import mean_squared_error, mean_absolute_error

warnings.filterwarnings('ignore')


# ====================== 1. Load LSTM-AE data ======================
def load_lstm_ae_data():
    """
    Load data prepared for LSTM-AE
    """
    print("📂 Loading LSTM-AE data (using DeepAE-generated virtual samples)...")

    # Directly use the virtual samples generated by DeepAE
    virtual_samples_path = r"D:\Oswaldo's surf project\My Database\virtual_samples_100000.npy"

    if not os.path.exists(virtual_samples_path):
        print(f"❌ DeepAE virtual samples file not found: {virtual_samples_path}")
        print("Please run DeepAE_realize.py first to generate the data")
        return None, None, None

    try:
        # Load data
        X_lstm = np.load(virtual_samples_path)

        print("✅ LSTM-AE data loaded successfully:")
        print(f"  Sequence data shape: {X_lstm.shape}")
        print(f"  Number of samples: {X_lstm.shape[0]:,}")
        print(f"  Timesteps: {X_lstm.shape[1]} hours ({X_lstm.shape[1] // 24} days)")
        print(f"  Number of features: {X_lstm.shape[2]}")
        print(f"  Data source: DeepAE virtual samples")

        # Load feature mapping
        feature_mapping_path = r"D:\Oswaldo's surf project\My Database\Merge_and_DAEfeature_mapping.json"
        with open(feature_mapping_path, 'r', encoding='utf-8') as f:
            feature_mapping = json.load(f)

        # Create config
        lstm_config = {
            "n_samples": X_lstm.shape[0],
            "sequence_hours": X_lstm.shape[1],
            "n_features": X_lstm.shape[2]
        }

        return X_lstm, lstm_config, feature_mapping

    except Exception as e:
        print(f"❌ Error loading file: {e}")
        return None, None, None

# ====================== 2. Build LSTM-AE model ======================
def build_lstm_autoencoder(sequence_length, n_features, lstm_units=128, encoding_dim=32):
    """
    Build LSTM Autoencoder model
    """
    print(f"\n🔧 Building LSTM-AutoEncoder model:")
    print(f"  Input shape: ({sequence_length}, {n_features})")
    print(f"  LSTM units: {lstm_units}")
    print(f"  Encoding dimension: {encoding_dim}")

    # ====== Encoder ======
    inputs = Input(shape=(sequence_length, n_features), name='lstm_input')

    # First LSTM layer
    encoded = LSTM(lstm_units, activation='relu', return_sequences=True,
                   name='encoder_lstm1')(inputs)
    encoded = BatchNormalization(name='encoder_bn1')(encoded)
    encoded = Dropout(0.3, name='encoder_dropout1')(encoded)

    # Second LSTM layer
    encoded = LSTM(lstm_units // 2, activation='relu', return_sequences=True,
                   name='encoder_lstm2')(encoded)
    encoded = BatchNormalization(name='encoder_bn2')(encoded)
    encoded = Dropout(0.3, name='encoder_dropout2')(encoded)

    # Third LSTM layer (does not return sequences)
    encoded = LSTM(lstm_units // 4, activation='relu', return_sequences=False,
                   name='encoder_lstm3')(encoded)

    # Bottleneck layer
    encoded = Dense(encoding_dim, activation='relu', name='bottleneck')(encoded)

    # ====== Decoder ======
    # Repeat vector
    decoded = RepeatVector(sequence_length, name='repeat_vector')(encoded)

    # First LSTM layer
    decoded = LSTM(lstm_units // 4, activation='relu', return_sequences=True,
                   name='decoder_lstm1')(decoded)
    decoded = BatchNormalization(name='decoder_bn1')(decoded)
    decoded = Dropout(0.3, name='decoder_dropout1')(decoded)

    # Second LSTM layer
    decoded = LSTM(lstm_units // 2, activation='relu', return_sequences=True,
                   name='decoder_lstm2')(decoded)
    decoded = BatchNormalization(name='decoder_bn2')(decoded)
    decoded = Dropout(0.3, name='decoder_dropout2')(decoded)

    # Third LSTM layer
    decoded = LSTM(lstm_units, activation='relu', return_sequences=True,
                   name='decoder_lstm3')(decoded)
    decoded = BatchNormalization(name='decoder_bn3')(decoded)

    # Output layer
    outputs = TimeDistributed(Dense(n_features, activation='linear'),
                              name='output')(decoded)

    # ====== Complete model ======
    autoencoder = Model(inputs, outputs, name='lstm_autoencoder')

    # Encoder model (for feature extraction)
    encoder = Model(inputs, encoded, name='lstm_encoder')

    return autoencoder, encoder


# ====================== 3. Data preparation function ======================
def prepare_lstm_train_val_split(X_lstm, train_ratio=0.85, val_ratio=0.15, shuffle=True):
    """
    Prepare training and validation data for LSTM-AE
    """
    n_samples = X_lstm.shape[0]

    if shuffle:
        # Random shuffle
        indices = np.random.permutation(n_samples)
        X_shuffled = X_lstm[indices]
    else:
        X_shuffled = X_lstm

    # Split training and validation sets
    train_end = int(n_samples * train_ratio)
    val_end = train_end + int(n_samples * val_ratio)

    X_train = X_shuffled[:train_end]
    X_val = X_shuffled[train_end:val_end]

    print(f"\n📊 LSTM dataset splitting:")
    print(f"  Training Set: {X_train.shape[0]:,} samples ({train_ratio * 100:.1f}%)")
    print(f"  Validation Set: {X_val.shape[0]:,} samples ({val_ratio * 100:.1f}%)")
    print(f"  Total Samples: {n_samples:,}")

    return X_train, X_val


# ====================== 4. Model training ======================
def train_lstm_autoencoder(X_train, X_val, sequence_length, n_features,
                           lstm_units=128, encoding_dim=32, epochs=80):
    """
    Train LSTM Autoencoder - optimized version
    """
    print(f"\n🚀 start training LSTM-AutoEncoder...")

    # Build model (unchanged)
    autoencoder, encoder = build_lstm_autoencoder(
        sequence_length=sequence_length,
        n_features=n_features,
        lstm_units=lstm_units,
        encoding_dim=encoding_dim
    )

    # 🔍 Add detailed parameter analysis
    print(f"\n📋 Model Architecture Summary:")
    autoencoder.summary(print_fn=lambda x: print(f"  {x}"))

    # Calculate detailed parameters
    total_params = autoencoder.count_params()
    trainable_params = np.sum([tf.keras.backend.count_params(w) for w in autoencoder.trainable_weights])
    non_trainable_params = total_params - trainable_params

    print(f"\n📊 model parameters count:")
    print(f"  Total parameters: {total_params:,}")
    print(f"  Trainable parameters: {trainable_params:,}")
    print(f"  Non-trainable parameters: {non_trainable_params:,}")
    # print(f"  Trainable ratio: {trainable_params / total_params * 100:.1f}%")

    # 🔧 Key optimization 1: Use mixed precision training (if GPU supports)
    from tensorflow.keras import mixed_precision
    try:
        policy = mixed_precision.Policy('mixed_float16')
        mixed_precision.set_global_policy(policy)
        print("✅ Mixed precision training enabled (accelerates GPU computation)")
    except:
        print("⚠️ Unable to enable mixed precision training, continuing with default precision")

    # Compile model
    autoencoder.compile(
        optimizer=Adam(learning_rate=0.001),
        loss='mse',
        metrics=['mae']
    )

    # 🔧 Key optimization 2: Adjust batch size (according to memory)
    # Reduce batch size to speed up individual epochs
    batch_size = 64  # Reduced from 128

    # 🔧 Key optimization 3: Simplify callbacks
    callbacks = [
        # EarlyStopping(
        #     monitor='val_loss',
        #     patience=8,  # Reduced patience
        #     restore_best_weights=True,
        #     verbose=1
        # ),
        ReduceLROnPlateau(
            monitor='val_loss',
            factor=0.5,
            patience=5,  # Reduced patience
            min_lr=1e-5,
            verbose=1
        )
    ]

    print(f"\n📈 Training Details:")
    print(f"  Batch Size: {batch_size}")
    print(f"  Max Epochs: {epochs}")

    # Train model
    history = autoencoder.fit(
        X_train, X_train,
        validation_data=(X_val, X_val),
        epochs=epochs,
        batch_size=batch_size,
        callbacks=callbacks,
        verbose=2  # More concise output
    )

    return autoencoder, encoder, history, autoencoder.count_params()


# ====================== 5. Evaluation and anomaly detection ======================
def evaluate_lstm_anomalies(autoencoder, X_val, X_test=None, percentile=95):
    """
    Evaluate LSTM-AE model and detect anomalies
    """
    print("\n📈 LSTM Model Evaluation Results:")

    # Evaluate on validation set
    val_loss, val_mae = autoencoder.evaluate(X_val, X_val, verbose=0)
    print(f"  Validation loss (MSE): {val_loss:.6f}")
    print(f"  Validation MAE: {val_mae:.6f}")

    # Calculate validation set reconstruction errors
    val_reconstructed = autoencoder.predict(X_val, verbose=0)

    # Compute average MSE per sample (averaged across timesteps and features)
    val_errors = np.mean((X_val - val_reconstructed) ** 2, axis=(1, 2))

    # Calculate threshold (95th percentile)
    threshold = np.percentile(val_errors, percentile)
    print(f"  Validation set reconstruction error {percentile}th percentile threshold: {threshold:.6f}")

    # Detect anomalies on test set if provided
    anomalies_count = 0
    anomaly_ratio = 0

    if X_test is not None:
        test_reconstructed = autoencoder.predict(X_test, verbose=0)
        test_errors = np.mean((X_test - test_reconstructed) ** 2, axis=(1, 2))

        # Detect anomalies
        anomalies = test_errors > threshold
        anomalies_count = np.sum(anomalies)
        anomaly_ratio = anomalies_count / len(X_test) * 100

        print(f"  Detected {anomalies_count} anomalous samples out of {len(X_test)} total samples")
        print(f"  Anomaly ratio: {anomaly_ratio:.2f}%")

        return threshold, anomalies_count, anomaly_ratio, test_errors, test_reconstructed, val_errors
    else:
        return threshold, 0, 0, val_errors, val_reconstructed, val_errors


# ====================== 6. Visualization functions ======================
def visualize_lstm_results(history, X_original, X_reconstructed, errors, threshold,
                           feature_mapping, model_name="LSTM AutoEncoder"):
    """
    Visualize LSTM-AE training results and anomaly detection
    """
    print(f"\n📊 Generating LSTM visualization results...")

    # Set plotting style
    plt.style.use('seaborn-v0_8-darkgrid')
    fig = plt.figure(figsize=(20, 12))

    # 1. Training loss history
    ax1 = plt.subplot(3, 3, 1)
    epochs = range(1, len(history.history['loss']) + 1)
    ax1.plot(epochs, history.history['loss'], label='Training Loss', linewidth=2)
    ax1.plot(epochs, history.history['val_loss'], label='Validation Loss', linewidth=2)
    ax1.set_title(f'{model_name} - Training History', fontsize=14, fontweight='bold')
    ax1.set_xlabel('Epoch', fontsize=12)
    ax1.set_ylabel('MSE Loss', fontsize=12)
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    # 2. MAE history
    ax2 = plt.subplot(3, 3, 2)
    ax2.plot(epochs, history.history['mae'], label='Training MAE', linewidth=2, color='orange')
    if 'val_mae' in history.history:
        ax2.plot(epochs, history.history['val_mae'], label='Validation MAE', linewidth=2, color='red')
    ax2.set_title('MAE History', fontsize=14, fontweight='bold')
    ax2.set_xlabel('Epoch', fontsize=12)
    ax2.set_ylabel('Mean Absolute Error', fontsize=12)
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    # 3. Reconstruction error distribution
    ax3 = plt.subplot(3, 3, 3)
    n_bins = min(100, len(errors) // 10)
    ax3.hist(errors, bins=n_bins, alpha=0.7, color='skyblue', edgecolor='black', density=True)
    ax3.axvline(x=threshold, color='red', linestyle='--', linewidth=2,
                label=f'Threshold ({threshold:.4f})')

    # Add Gaussian fit
    from scipy.stats import norm
    mu, std = norm.fit(errors)
    xmin, xmax = ax3.get_xlim()
    x = np.linspace(xmin, xmax, 100)
    p = norm.pdf(x, mu, std)
    ax3.plot(x, p, 'k', linewidth=2, label=f'Normal fit: μ={mu:.4f}, σ={std:.4f}')

    ax3.set_title('Reconstruction Error Distribution', fontsize=14, fontweight='bold')
    ax3.set_xlabel('Reconstruction Error (MSE)', fontsize=12)
    ax3.set_ylabel('Density', fontsize=12)
    ax3.legend()
    ax3.grid(True, alpha=0.3)

    # 4. Original vs reconstructed feature comparison (first sample, first feature)
    ax4 = plt.subplot(3, 3, 4)
    if len(X_original) > 0:
        sample_idx = 0
        feature_idx = 0  # Display first feature

        # Get all timesteps of the first sample
        time_steps = range(X_original[sample_idx].shape[0])
        original_values = X_original[sample_idx][:, feature_idx]
        reconstructed_values = X_reconstructed[sample_idx][:, feature_idx]

        ax4.plot(time_steps, original_values, label='Original', linewidth=2, alpha=0.8)
        ax4.plot(time_steps, reconstructed_values, label='Reconstructed', linewidth=2,
                 alpha=0.8, color='red', linestyle='--')

        ax4.set_title(f'Sample {sample_idx} - Feature {feature_idx} Comparison',
                      fontsize=14, fontweight='bold')
        ax4.set_xlabel('Time Step', fontsize=12)
        ax4.set_ylabel('Feature Value', fontsize=12)
        ax4.legend()
        ax4.grid(True, alpha=0.3)

    # 5. Reconstruction error time series
    ax5 = plt.subplot(3, 3, 5)
    sample_indices = range(len(errors))

    # Smooth errors
    window_size = min(100, len(errors) // 10)
    if window_size > 1:
        errors_smooth = np.convolve(errors, np.ones(window_size) / window_size, mode='valid')
        indices_smooth = sample_indices[:len(errors_smooth)]
        ax5.plot(indices_smooth, errors_smooth, linewidth=1, alpha=0.7, color='blue',
                 label='Smoothed Error')

    ax5.plot(sample_indices, errors, linewidth=0.5, alpha=0.3, color='gray', label='Raw Error')
    ax5.axhline(y=threshold, color='red', linestyle='--', linewidth=2,
                label=f'Threshold ({threshold:.4f})')

    # Mark anomalies
    anomalies = errors > threshold
    anomaly_indices = np.where(anomalies)[0]
    ax5.scatter(anomaly_indices, errors[anomaly_indices],
                color='red', s=10, alpha=0.5, label='Anomalies')

    ax5.set_title('Reconstruction Error Time Series', fontsize=14, fontweight='bold')
    ax5.set_xlabel('Sample Index', fontsize=12)
    ax5.set_ylabel('Reconstruction Error', fontsize=12)
    ax5.legend(loc='upper right', fontsize=10)
    ax5.grid(True, alpha=0.3)

    # 6. Error box plot
    ax6 = plt.subplot(3, 3, 6)
    box_data = [errors[~anomalies], errors[anomalies]] if len(anomaly_indices) > 0 else [errors]
    box_labels = ['Normal', 'Anomaly'] if len(anomaly_indices) > 0 else ['All Samples']

    bp = ax6.boxplot(box_data, labels=box_labels, patch_artist=True)

    # Set colors
    colors = ['lightblue', 'lightcoral'] if len(anomaly_indices) > 0 else ['lightblue']
    for patch, color in zip(bp['boxes'], colors):
        patch.set_facecolor(color)

    ax6.axhline(y=threshold, color='red', linestyle='--', linewidth=1.5)
    ax6.set_title('Error Distribution by Category', fontsize=14, fontweight='bold')
    ax6.set_ylabel('Reconstruction Error', fontsize=12)
    ax6.grid(True, alpha=0.3, axis='y')

    # 7. Learning rate schedule
    ax7 = plt.subplot(3, 3, 7)
    if 'lr' in history.history:
        ax7.plot(epochs, history.history['lr'], linewidth=2, color='green')
        ax7.set_title('Learning Rate Schedule', fontsize=14, fontweight='bold')
        ax7.set_xlabel('Epoch', fontsize=12)
        ax7.set_ylabel('Learning Rate', fontsize=12)
        ax7.grid(True, alpha=0.3)
    else:
        ax7.text(0.5, 0.5, 'Learning Rate\nData Not Available',
                 ha='center', va='center', transform=ax7.transAxes, fontsize=12)
        ax7.set_title('Learning Rate Schedule', fontsize=14, fontweight='bold')

    # 8. Feature reconstruction error heatmap (first sample)
    ax8 = plt.subplot(3, 3, 8)
    if len(X_original) > 0:
        sample_idx = 0
        feature_errors = (X_original[sample_idx] - X_reconstructed[sample_idx]) ** 2

        im = ax8.imshow(feature_errors.T, aspect='auto', cmap='YlOrRd')
        ax8.set_xlabel('Time Step', fontsize=12)
        ax8.set_ylabel('Feature Index', fontsize=12)
        ax8.set_title(f'Sample {sample_idx} Feature-wise Reconstruction Error',
                      fontsize=14, fontweight='bold')
        plt.colorbar(im, ax=ax8, label='Reconstruction Error')

        # Set y-axis labels (feature names)
        if 'hour_feature_names' in feature_mapping:
            hour_feature_names = feature_mapping['hour_feature_names']
            if len(hour_feature_names) == X_original.shape[2]:
                ax8.set_yticks(range(0, len(hour_feature_names), 3))
                ax8.set_yticklabels([hour_feature_names[i] for i in range(0, len(hour_feature_names), 3)])

    # 9. Anomaly detection performance
    ax9 = plt.subplot(3, 3, 9)
    if np.sum(errors > threshold) > 0:
        # Compute performance at different thresholds
        thresholds = np.percentile(errors, range(90, 100))
        anomaly_rates = []

        for t in thresholds:
            anomaly_rate = np.sum(errors > t) / len(errors) * 100
            anomaly_rates.append(anomaly_rate)

        ax9.plot(thresholds, anomaly_rates, 'o-', linewidth=2, markersize=6)
        ax9.axvline(x=threshold, color='red', linestyle='--', linewidth=1.5,
                    label=f'95th percentile ({threshold:.4f})')
        ax9.set_title('Anomaly Rate vs Threshold', fontsize=14, fontweight='bold')
        ax9.set_xlabel('Threshold', fontsize=12)
        ax9.set_ylabel('Anomaly Rate (%)', fontsize=12)
        ax9.legend()
        ax9.grid(True, alpha=0.3)
    else:
        ax9.text(0.5, 0.5, 'No Anomalies Detected\nwith Current Threshold',
                 ha='center', va='center', transform=ax9.transAxes, fontsize=12)
        ax9.set_title('Anomaly Detection Performance', fontsize=14, fontweight='bold')

    plt.tight_layout()

    # Save figure
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    save_path = f"D:\\Oswaldo's surf project\\My Database\\lstm_visualization_{timestamp}.png"
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    print(f"📸 LSTM visualization results saved to: {save_path}")

    plt.close()

    # Output feature-level analysis
    if len(X_original) > 0:
        print("\n📊 LSTM Reconstruction Error Analysis (First Sample):")
        feature_errors = np.mean((X_original[0] - X_reconstructed[0]) ** 2, axis=0)

        if 'hour_feature_names' in feature_mapping:
            hour_feature_names = feature_mapping['hour_feature_names']
            if len(hour_feature_names) == len(feature_errors):
                print("  Feature Reconstruction Error Ranking:")
                sorted_indices = np.argsort(feature_errors)[::-1]
                for i, idx in enumerate(sorted_indices[:5]):
                    print(f"    {i + 1}. {hour_feature_names[idx]}: {feature_errors[idx]:.6f}")


# ====================== 7. Encoded feature analysis ======================
def encode_and_analyze_lstm(encoder, X, feature_mapping):
    """
    Extract features using LSTM encoder and perform analysis
    """
    print("\n🔍 LSTM Feature Encoding and Analysis:")

    # Extract encoded features
    encoded_features = encoder.predict(X, verbose=0)
    print(f"  Encoded feature shape: {encoded_features.shape}")

    # Calculate compression ratio
    original_size = X.shape[1] * X.shape[2]  # timesteps × features
    encoded_size = encoded_features.shape[1]
    compression_ratio = original_size / encoded_size

    print(f"  Compression ratio: {original_size}:{encoded_size} = {compression_ratio:.1f}x")
    print(f"  Original dimension: {original_size} → Encoded dimension: {encoded_size}")

    return encoded_features


# ====================== 8. Save models ======================
def save_lstm_models(autoencoder, encoder, save_path):
    """
    Save trained LSTM models
    """
    # Ensure save path exists
    os.makedirs(save_path, exist_ok=True)

    # Save as HDF5 format
    autoencoder.save(f"{save_path}lstm_autoencoder_model2.h5")
    encoder.save(f"{save_path}lstm_encoder_model2.h5")

    print(f"\n💾 LSTM model saved to: {save_path}")
    print(f"  - lstm_autoencoder_model2.h5")
    print(f"  - lstm_encoder_model2.h5")


def setup_environment():
    """Set up optimized environment"""
    import os
    os.environ['TF_ENABLE_ONEDNN_OPTS'] = '1'  # Enable oneDNN optimizations
    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # Reduce TensorFlow logs
    os.environ['OMP_NUM_THREADS'] = str(os.cpu_count())  # Use all CPU cores
    print(f"✅ uses {os.cpu_count()} CPU core")

# ====================== 9. Main workflow ======================
def main():
    print("=" * 80)
    print("LSTM AUTOENCODER TRAINING PIPELINE")
    print("=" * 80)

    # Configure paths
    base_path = r"D:\Oswaldo's surf project\My Database"
    model_save_path = os.path.join(base_path, "models\\")

    # 1. Load LSTM-AE data
    X_lstm, lstm_config, feature_mapping = load_lstm_ae_data()
    if X_lstm is None:
        print("❌ Failed to load LSTM data, exiting process")
        return

    # 2. Prepare training data
    X_train, X_val = prepare_lstm_train_val_split(
        X_lstm,
        train_ratio=0.85,
        val_ratio=0.15,
        shuffle=True
    )

    # 3. Train LSTM Autoencoder
    sequence_length = X_lstm.shape[1]
    n_features = X_lstm.shape[2]

    autoencoder, encoder, history, total_params = train_lstm_autoencoder(
        X_train, X_val,
        sequence_length=sequence_length,
        n_features=n_features,
        lstm_units=128,
        encoding_dim=32,
        epochs=80
    )

    # 4. Evaluate on validation set
    print("\n🔍 Evaluating LSTM model on validation set:")
    threshold, val_anomalies_count, val_anomaly_ratio, val_errors, val_reconstructed, val_errors_full = evaluate_lstm_anomalies(
        autoencoder, X_val, X_val, percentile=95
    )

    # 5. Evaluate on the complete dataset
    print("\n🔍 Evaluating on the complete LSTM dataset:")
    # Use all 100000 samples for evaluation
    X_all = X_lstm

    all_reconstructed = autoencoder.predict(X_all, verbose=0)
    all_errors = np.mean((X_all - all_reconstructed) ** 2, axis=(1, 2))

    # Detect anomalies
    all_anomalies = all_errors > threshold
    all_anomalies_count = np.sum(all_anomalies)
    all_anomaly_ratio = all_anomalies_count / len(X_all) * 100

    print(f"  Total samples: {len(X_all):,}")
    print(f"  Anomalies detected: {all_anomalies_count:,}")
    print(f"  Anomaly proportion: {all_anomaly_ratio:.2f}%")

    # 6. Visualize results
    print("\n📊 Generating visualization for all LSTM samples:")
    visualize_lstm_results(
        history, X_all, all_reconstructed, all_errors, threshold,
        feature_mapping, model_name="LSTM AutoEncoder (100000 samples)"
    )

    # 7. Feature encoding and analysis
    encoded_features = encode_and_analyze_lstm(encoder, X_all, feature_mapping)

    # 8. Save models
    save_lstm_models(autoencoder, encoder, model_save_path)

    # 9. Generate analysis report
    print("\n" + "=" * 80)
    print("📋 LSTM Training Completion Report")
    print("=" * 80)

    # Output in consistent format with DeepAE
    print(f"\n📊 LSTM Model Performance Summary:")
    print(f"  Total samples: {X_lstm.shape[0]:,}")
    print(f"  Actual training samples used: {X_train.shape[0]:,}")
    print(f"  Actual validation samples used: {X_val.shape[0]:,}")
    print(f"  Total params: {total_params:,}")
    print(f"  Validation loss (MSE): {history.history['val_loss'][-1]:.6f}")
    print(f"  95th percentile threshold (validation): {threshold:.6f}")
    print(f"  Anomaly detection (all samples): {all_anomalies_count:,} / {len(X_all):,} ({all_anomaly_ratio:.2f}%)")

    # 10. Save detailed results
    results = {
        'model_name': 'LSTM_AutoEncoder',
        'total_params': int(total_params),
        'n_samples': X_lstm.shape[0],
        'n_train_samples': X_train.shape[0],
        'n_val_samples': X_val.shape[0],
        'sequence_length': int(sequence_length),
        'sequence_days': int(sequence_length // 24),
        'n_features': int(n_features),
        'lstm_units': 128,
        'encoding_dim': 32,
        'validation_threshold': float(threshold),
        'validation_anomalies': int(val_anomalies_count),
        'all_anomalies': int(all_anomalies_count),
        'anomaly_ratio_all': float(all_anomaly_ratio),
        'anomaly_ratio_val': float(val_anomaly_ratio),
        'final_train_loss': float(history.history['loss'][-1]),
        'final_val_loss': float(history.history['val_loss'][-1]),
        'final_train_mae': float(history.history['mae'][-1]),
        'final_val_mae': float(history.history.get('val_mae', [0])[-1]),
        'training_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        'compression_ratio': float((sequence_length * n_features) / 32),
        'data_shape': list(X_lstm.shape)
    }

    results_path = os.path.join(base_path, 'lstm_ae_training_results2.json')
    with open(results_path, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    print(f"\n💾 LSTM training results saved to: {results_path}")
    print("\n🎉 LSTM AutoEncoder training pipeline completed！")


# ====================== 10. Run main workflow ======================
if __name__ == "__main__":
    # Set TensorFlow logging level
    tf.get_logger().setLevel('ERROR')

    # Set matplotlib font for minus signs
    # plt.rcParams['font.sans-serif'] = ['SimHei', 'DejaVu Sans']
    plt.rcParams['axes.unicode_minus'] = False

    # Run main workflow
    main()
