[env:esp32-s3-dev]
platform = espressif32
board = my_esp32-s3-32mb
board_build.mcu = esp32s3
board_build.flash_mode = qio          ; 新增：临时使用 QIO 模式
board_build.flash_size = 32MB
board_build.partitions = partitions_32MB.csv
board_build.psram = enable
board_build.psram_mode = octal
board_build.psram_freq = 80MHz
board_build.flash_voltage = 1.8V
board_build.filesystem = spiffs
framework = espidf
board_build.espidf.version = v5.6.0  ; 指定 ESP-IDF 版本
monitor_speed = 115200



upload_port = COM7

build_flags = 
    -std=gnu++14

    -DMODEL_FILENAME=\"/spiffs/conv_100k_model.tflite\"

    ; -DMODEL_INDEX=2

    -DRUN_EVERY_MINUTES=10
    -DMINUTE_SAMPLE_PERIOD_SEC=60
    -DNOISE_DB_TH=65.0f
    -DREFRACTORY_SEC=5
    -DMAE_THRESHOLD=0.078524f

    -DTF_LITE_STATIC_MEMORY
    -DTF_LITE_REMOVE_VIRTUAL_DELETE=
    -Wno-sign-compare
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

   

    -Ilib/esp-tflite-micro
    -Ilib/esp-tflite-micro/tensorflow/lite/micro
    -Ilib/esp-tflite-micro/third_party/flatbuffers/include
    -Ilib/esp-tflite-micro/third_party/gemmlowp
    -Ilib/esp-tflite-micro/third_party/ruy